---
creation_rules:
  - path_regex: kubernetes/.+\.sops\.ya?ml.j2
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - age1lz2u75apdq73zpxp039khxngs59jcca5ek8apc8c02eceg25asrq55u5dc
  - path_regex: talos/.*\.sops\.ya?ml
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|secretboxencryptionsecret|bootstraptoken|ca)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - age1lz2u75apdq73zpxp039khxngs59jcca5ek8apc8c02eceg25asrq55u5dc
  - path_regex: kubernetes/.+\.sops\.ya?ml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - age1lz2u75apdq73zpxp039khxngs59jcca5ek8apc8c02eceg25asrq55u5dc
stores:
  yaml:
    indent: 2
