---
creation_rules:
  - # IMPORTANT: Keep this rule first
    path_regex: talos/.*\.sops\.ya?ml
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    age: age1lz2u75apdq73zpxp039khxngs59jcca5ek8apc8c02eceg25asrq55u5dc
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: ^(data|stringData)$
    age: age1lz2u75apdq73zpxp039khxngs59jcca5ek8apc8c02eceg25asrq55u5dc
