---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  bootstrap: .taskfiles/bootstrap
  flux: .taskfiles/flux
  kubernetes: .taskfiles/kubernetes
  sops: .taskfiles/sops
  talos: .taskfiles/talos
  workstation: .taskfiles/workstation

vars:
  CLUSTER_DIR: '{{.ROOT_DIR}}/kubernetes'
  BOOTSTRAP_DIR: '{{.CLUSTER_DIR}}/bootstrap'

env:
  KUBECONFIG: '{{.CLUSTER_DIR}}/kubeconfig'
  MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.CLUSTER_DIR}}/talosconfig'

tasks:
  default:
    cmd: task --list
    silent: true
