---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  bootstrap: .taskfiles/Bootstrap
  flux: .taskfiles/Flux
  sops: .taskfiles/Sops
  talos: .taskfiles/Talos

vars:
  # Directories
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'
  # Files
  AGE_FILE: '{{.ROOT_DIR}}/age.key'
  CONFIG_FILE: '{{.ROOT_DIR}}/config.yaml'
  KUBECONFIG_FILE: '{{.ROOT_DIR}}/kubeconfig'
  SOPS_CONFIG_FILE: '{{.ROOT_DIR}}/.sops.yaml'

env:
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'

tasks:
  default: task -l
