---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

set: [pipefail]
shopt: [globstar]

includes:
  bootstrap: .taskfiles/bootstrap
  kubernetes: .taskfiles/kubernetes
  sops: .taskfiles/sops
  talos: .taskfiles/talos
  workstation: .taskfiles/workstation

vars:
  CLUSTER_DIR: '{{.ROOT_DIR}}/kubernetes'
  BOOTSTRAP_DIR: '{{.CLUSTER_DIR}}/bootstrap'

env:
  KUBECONFIG: '{{.ROOT_DIR}}/kubernetes/kubeconfig'
  MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.ROOT_DIR}}/kubernetes/talosconfig'

dotenv: ['{{.BOOTSTRAP_DIR}}/.cluster.env']

tasks:
  default:
    cmd: task --list
    silent: true

  reconcile:
    desc: Force Fux to pull in changes from your Git repository
    cmd: flux --namespace flux-system reconcile kustomization flux-system --with-source
    preconditions:
      - test -f {{.KUBECONFIG}}
      - which
