---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: debrid-media-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      debrid-media-manager:
        containers:
          app:
            image:
              repository: debridmediamanager/debrid-media-manager
              tag: 4.0.0
            env:
              EXTERNAL_SEARCH_API_HOSTNAME: https://corsproxy.org/?https://debridmediamanager.com
            ports:
              - name: http
                containerPort: 3000
                protocol: TCP
    service:
      app:
        controller: debrid-media-manager
        type: ClusterIP
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: external
        hosts:
          - host: debrid.mordex.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    # route:
    # http:
    #   kind: HTTPRoute
    #   labels:
    #     route-type: external
    #   parentRefs:
    #     - name: traefik-external-gateway
    #       sectionName: web
    #       namespace: network
    #   hostnames:
    #     - debrid.mordex.io
    #   rules:
    #     - filters:
    #         - type: RequestRedirect
    #           requestRedirect:
    #             scheme: https
    # https:
    #   kind: HTTPRoute
    #   labels:
    #     route-type: external
    #   parentRefs:
    #     - name: traefik-external-gateway
    #       sectionName: websecure
    #       namespace: network
    #   hostnames:
    #     - debrid.mordex.io
    #   rules:
    #     - matches:
    #         - path:
    #             type: PathPrefix
    #             value: /
    #       backendRefs:
    #         - name: app
    #           port: 3000
