---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./external-secret.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: home-assistant-configmap
    files:
      - configuration.yaml=./resources/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
