---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: v32.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    deployment:
      replicas: 3

    gateway:
      listeners:
        web:
          namespacePolicy: All
        websecure:
          namespacePolicy: All
          port: 8443
          protocol: HTTPS
          certificateRefs:
            - kind: Secret
              name: home-mordex-io-tls
              namespace: cert-manager
          mode: Terminate
        traefik:
          port: 8080
          protocol: HTTPS
          certificateRefs:
            - kind: Secret
              name: home-mordex-io-tls
              namespace: cert-manager
          mode: Terminate

    providers:
      # kubernetesCRD:
      #   enabled: true
      #   ingressClass: traefik-internal
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true

    logs:
      general:
        level: 'DEBUG'

    globalArguments:
      - '--global.sendanonymoususage=false'
      - '--global.checknewversion=false'

    ports:
      traefik:
        port: 8080
      web:
        redirectTo:
          port: websecure
          priority: 10

    service:
      annotations:
        lbipam.cilium.io/ips: 10.30.0.100
      spec:
        loadBalancerIP: 10.30.0.100
