---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: homepage
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
