---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-operator-crds
      version: 16.0.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
