---
version: '3'

tasks:
  bootstrap:
    desc: Bootstrap Flux onto a k8s cluster
    summary: |
      CLUSTER: The cluster name to bootstrap
    cmds:
      - GITHUB_TOKEN={{.GITHUB_FLUX_PAT}} flux bootstrap github --context={{.CLUSTER}} --owner=mmberry96 --repository=HomeOps --branch=master --personal --path=kubernetes/clusters/{{.CLUSTER}} --token-auth
      - cat {{.AGE_FILE}} | kubectl create secret generic sops-age --kubeconfig {{.KUBECONFIG_FILE}} --context {{.CLUSTER}} -n flux-system --from-file=age.agekey=/dev/stdin
    requires:
      vars: [CLUSTER]
    preconditions:
      - msg: Missing kubeconfig
        sh: test -f {{.KUBECONFIG_FILE}}
      - msg: Missing Github PAT, create .env file with it (see sample.env for example)
        sh: test -n {{.GITHUB_FLUX_PAT}}
