---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  reconcile:
    desc: Force update Flux to pull in changes from your Git repository
    summary: |
      CLUSTER: Cluster to run command against (default: main)
    vars:
      CLUSTER: '{{.CLUSTER | default "home-kubernetes"}}'
    cmd: flux --context {{.CLUSTER}} reconcile --namespace flux-system kustomization cluster --with-source
