apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lz2u75apdq73zpxp039khxngs59jcca5ek8apc8c02eceg25asrq55u5dc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQzljalNKSlh5M205eHhu
            K0V6UmpBV0xOa0tJVjZPZVBGVnNDT1lpemxjCjc1VzNjN1RQMWIvb2dEN1FJYnZr
            REFVVlpNejErRFhhOURPTDN6UDd6OWcKLS0tIEdWK1dsb1lMTERMcGxpekNjbDYr
            encvZWx0NEU2bFZqdnd3UUdoOFZVRlUKccKi1Y7dVWI+XIo9Uzc9CAQXksnmZAQU
            RFclyY8gOU9QRptrtN3TrJbuCccy7CjeS1RvVNi54g7B+k5b6A+lJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T08:08:17Z"
    mac: ENC[AES256_GCM,data:qYDNYdqNS/mjzvemu3JxQghtltMQ0vwTMvWOKsv/ew0WrDPfOSuJ0evilY5GeA3Zld5+Kj8VeBWH/1unF75/qGn3W+gs8QOZ7ygBEToBPA7FUn1BZ2YjOcXY1jmosxvD2qHDIlatSXKsXJXMA5+CFyiSe24dJGYR+GmzpSLdxrg=,iv:sgpjR7GHJ2chvopCBH5yuTq2n1yXUvI+EBwO25lCYJY=,tag:75jqDaggZ51DdT7bJaLoIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
