---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./homepage/ks.yaml
  - ./plex/ks.yaml
patches:
  - patch: |
      - op: add
        path: /spec/dependsOn/-
        value:
          name: traefik-internal
    target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io/v1
      namespace: flux-system
