---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: 'Yes'
  blocks:
    - # Controller VIP: 10.30.0.40
      start: 10.30.0.100
      stop: 10.30.0.119
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  interfaces: ['^eno.*']
  # interfaces: [bond0.30]
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: kube-api
  annotations:
    io.cilium/lb-ipam-ips: 10.30.0.40
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  ports:
    - name: https
      port: 6443
      protocol: TCP
      targetPort: 6443
