---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./node-feature-discovery.yaml
  - ./postfinance.yaml
  - ./stakater.yaml
  - ./traefik.yaml
