---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http
  labels:
    route-type: internal
spec:
  parentRefs:
    - name: traefik-internal-gateway
      sectionName: web
      namespace: network
  hostnames:
    - grafana.mordex.io
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-https
  labels:
    route-type: internal
spec:
  parentRefs:
    - name: traefik-internal-gateway
      sectionName: websecure
      namespace: network
  hostnames:
    - grafana.mordex.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana
          port: 80
