---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-http
  labels:
    route-type: internal
spec:
  parentRefs:
    - name: traefik-internal-gateway
      sectionName: web
      namespace: network
  hostnames:
    - hubble.mordex.io
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-https
  labels:
    route-type: internal
spec:
  parentRefs:
    - name: traefik-internal-gateway
      sectionName: websecure
      namespace: network
  hostnames:
    - hubble.mordex.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hubble-ui
          port: 80
