---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
    - name: generic-device-plugin
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: 'true'
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            # Ensure that Plex and Zurg pods run on same node
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: plex
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      plex:
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: 'true'
        initContainers:
          zurg:
            restartPolicy: Always
            image:
              repository: ghcr.io/mmberry96/zurg
              tag: 0.1.9@sha256:4063adf52782b8b74fa3c250ca637908b6ccc5b297710489ebf44bc3b17cbd0e
            envFrom:
              - secretRef:
                  name: debrid-api-token
            probes:
              liveness: &zurg-probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /dav/version.txt
                    port: 9999
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *zurg-probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - 'ALL'
          rclone:
            image:
              repository: rclone/rclone
              tag: 1.68.1
            args:
              - mount
              - 'zurg:'
              - '/data'
              - --allow-non-empty
              - --allow-other
              - --uid=65534
              - --gid=65534
              - --umask=002
              - --vfs-cache-mode=full
              - --vfs-cache-max-size=50G
              - --vfs-refresh
              - --user-agent=plex
              - --buffer-size=64Mi
              - --rc
              - -vv
            env:
              RCLONE_CONFIG: /config/rclone/rclone.conf
            dependsOn:
              - zurg
            securityContext:
              privileged: true
              capabilities:
                drop:
                  - 'ALL'
                add:
                  - 'SYS_ADMIN'
            resources:
              limits:
                squat.ai/fuse: 1
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.41.0.8994-f2c27da23@sha256:fe9ed1189617cd98106635c63ed39d40e4ec82535514e4a51a7c72e56b65c4dd
            env:
              TZ: America/Chicago
              PLEX_ADVERTISE_URL: https://plex.home.mordex.io:443,http://10.30.0.100:32400
              PLEX_NO_AUTH_NETWORKS: 10.10.0.0/24
            probes:
              liveness: &plex-probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *plex-probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - 'ALL'
            resources:
              requests:
                cpu: 100m
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi
    service:
      plex:
        controller: plex
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.30.0.101
        ports:
          http:
            port: 32400
      zurg:
        controller: plex
        type: ClusterIP
        ports:
          http:
            port: 9999
    route:
      http:
        kind: HTTPRoute
        parentRefs:
          - name: traefik-gateway
            sectionName: web
            namespace: network
        hostnames:
          - plex.home.mordex.io
        rules:
          - filters:
              - type: RequestRedirect
                requestRedirect:
                  scheme: https
      https:
        kind: HTTPRoute
        parentRefs:
          - name: traefik-gateway
            sectionName: websecure
            namespace: network
        hostnames:
          - plex.home.mordex.io
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: plex
                port: 32400
    persistence:
      config:
        existingClaim: plex
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server
      transcode:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /transcode
      zurg-config:
        type: configMap
        name: zurg-configmap
        advancedMounts:
          plex:
            rclone:
              - path: /config/rclone/rclone.conf
                subPath: rclone
            zurg:
              - path: /app/zurg_template.yml
                subPath: zurg
      logs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs
            zurg:
              - path: /app/logs
      cache:
        type: emptyDir
        advancedMounts:
          plex:
            rclone:
              - path: /.cache
      media:
        type: nfs
        server: truenas.home.mordex.io
        path: /mnt/storage0/media
        advancedMounts:
          plex:
            app:
              - path: /media
                readOnly: true
      zurg-data:
        existingClaim: zurg-data
        advancedMounts:
          plex:
            zurg:
              - path: /app/data
      torrents:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /debrid
                readOnly: true
                mountPropagation: HostToContainer
            rclone:
              - path: /data
                mountPropagation: Bidirectional
