---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  # - ./debrid-media-manager/ks.yaml
  - ./home-assistant/ks.yaml
  - ./homepage/ks.yaml
  - ./kavita/ks.yaml
  - ./plex/ks.yaml
components:
  - ../../flux/components/alerts
  - ../../flux/components/namespace
  - ../../flux/components/sops
