---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./homepage/ks.yaml
  - ./plex/debrid.secret.sops.yaml # Secret created here to avoid targetNamespace from ks.yaml to get secret into flux-system namespace
  - ./plex/ks.yaml
