---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: v33.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    deployment:
      replicas: 2
    ingressClass:
      enabled: false
    gateway:
      name: traefik-external-gateway
      listeners:
        web:
          namespacePolicy: All
        websecure:
          namespacePolicy: All
          port: 8443
          protocol: HTTPS
          certificateRefs:
            - kind: Secret
              name: mordex-io-tls
              namespace: network
          mode: Terminate
    gatewayClass:
      name: traefik-external
    providers:
      kubernetesCRD:
        enabled: false
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
        statusAddress:
          ip: 10.30.0.105
          hostname: external.mordex.io
    globalArguments:
      - '--global.sendanonymoususage=false'
      - '--global.checknewversion=false'
    ports:
      web:
        redirectTo:
          port: websecure
          priority: 10
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: external.mordex.io
        lbipam.cilium.io/ips: 10.30.0.105
      spec:
        loadBalancerIP: 10.30.0.105
