---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  TALOS_SECRETS_FILE: '{{.CLUSTER_DIR}}/talos/talos_secrets.sops.yaml'

tasks:
  create-config:
    desc: Generate a new Talos configuration file [CLUSTER=main] [IP=required] [ENDPOINT=required] [NODE_TYPE=controlplane]
    cmds:
      - sops exec-file --input-type yaml --output-type yaml {{.TALOS_SECRETS_FILE}} "talosctl gen config --with-secrets {} --output-types {{.NODE_TYPE}} --output {{.FILENAME}} --with-docs=false --with-examples=false {{.CLUSTER}} {{.ENDPOINT}}"
      - sops encrypt --in-place --input-type yaml --output-type yaml {{.FILENAME}}
    vars:
      NODE_TYPE: '{{.NODE_TYPE | default "controlplane"}}'
      FILENAME: '{{.CLUSTER_DIR}}/talos/{{.IP}}.sops.yaml.j2'
    requires:
      vars: [CLUSTER, IP, ENDPOINT]
    status:
      - test -f {{.FILENAME}}
    preconditions:
      - test -f {{.TALOS_SECRETS_FILE}}
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which sops talosctl

  apply-node:
    desc: Apply Talos config to a node [CLUSTER=main] [IP=required] [MODE=auto]
    dotenv: ['{{.CLUSTER_DIR}}/cluster.env']
    cmds:
      - task: down
      - sops exec-file --input-type yaml --output-type yaml {{.CLUSTER_DIR}}/talos/{{.IP}}.sops.yaml.j2 "minijinja-cli {}" | talosctl --nodes {{.IP}} apply-config --mode={{.MODE}} --file /dev/stdin
      - talosctl --nodes {{.IP}} health
      - task: up
    vars:
      MODE: '{{.MODE | default "auto"}}'
    requires:
      vars: [CLUSTER, IP]
    preconditions:
      - talosctl --nodes {{.IP}} get machineconfig
      - test -f {{.CLUSTER_DIR}}/cluster.env
      - test -f {{.CLUSTER_DIR}}/talos/{{.IP}}.sops.yaml.j2
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which minijinja-cli sops talosctl

  upgrade-node:
    desc: Upgrade Talos on a single node [CLUSTER=main] [IP=required]
    dotenv: ['{{.CLUSTER_DIR}}/cluster.env']
    cmds:
      - task: down
      - talosctl --nodes {{.IP}} upgrade --image="factory.talos.dev/install/{{.TALOS_SCHEMATIC_ID}}:$TALOS_VERSION" --timeout=10m
      - talosctl --nodes {{.IP}} health
      - task: up
    vars:
      TALOS_SCHEMATIC_ID:
        sh: talosctl --nodes {{.IP}} get nodeannotationspecs --output json | jq --raw-output '.spec | select(.key == "extensions.talos.dev/schematic") | .value'
    requires:
      vars: [CLUSTER, IP]
    preconditions:
      - curl -fsSL -o /dev/null --fail https://github.com/siderolabs/talos/releases/tag/$TALOS_VERSION
      - talosctl --nodes {{.IP}} get machineconfig
      - talosctl config info
      - test -f {{.CLUSTER_DIR}}/cluster.env
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which jq talosctl

  upgrade-k8s:
    desc: Update Kubernetes across the whole cluster [CLUSTER=main]
    dotenv: ['{{.CLUSTER_DIR}}/cluster.env']
    cmds:
      - task: down
      - talosctl --nodes {{.TALOS_CONTROLLER}} upgrade-k8s --to $KUBERNETES_VERSION
      - task: up
    vars:
      TALOS_CONTROLLER:
        sh: talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1
    requires:
      vars: [CLUSTER]
    preconditions:
      - curl -fsSL -o /dev/null --fail https://github.com/siderolabs/kubelet/releases/tag/$KUBERNETES_VERSION
      - talosctl --nodes {{.TALOS_CONTROLLER}} get machineconfig
      - talosctl config info
      - test -f {{.CLUSTER_DIR}}/cluster.env
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which jq talosctl

  reboot-node:
    desc: Reboot Talos on a single node [CLUSTER=main] [IP=required] [MODE=default]
    cmds:
      - task: down
      - talosctl --nodes {{.IP}} reboot --mode={{.MODE}}
      - talosctl --nodes {{.IP}} health
      - task: up
    vars:
      MODE: '{{.MODE | default "default"}}'
    requires:
      vars: [CLUSTER, IP]
    preconditions:
      - talosctl --nodes {{.IP}} get machineconfig
      - talosctl config info
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which talosctl

  shutdown-cluster:
    desc: Shutdown Talos across the whole cluster [CLUSTER=main]
    prompt: Shutdown the Talos cluster '{{.CLUSTER}}'... continue?
    cmd: talosctl shutdown --nodes {{.NODES}} --force
    vars:
      NODES:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(",")'
    requires:
      vars: [CLUSTER]
    preconditions:
      - talosctl --nodes {{.NODES}} get machineconfig
      - talosctl config info
      - test -f {{.CLUSTER_DIR}}/cluster.env
      - which jq talosctl

  reset-node:
    desc: Reset Talos on a single node [CLUSTER=main] [IP=required]
    prompt: Reset Talos node '{{.IP}}' on the '{{.CLUSTER}}' cluster ... continue?
    cmd: talosctl reset --nodes {{.IP}} --graceful=false --reboot=true
    requires:
      vars: [CLUSTER, IP]
    preconditions:
      - talosctl --nodes {{.IP}} get machineconfig
      - talosctl config info
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which talosctl

  reset-cluster:
    desc: Reset Talos across the whole cluster [CLUSTER=main]
    prompt: Reset the Talos cluster '{{.CLUSTER}}' ... continue?
    cmd: talosctl reset --nodes {{.NODES}} --graceful=false
    vars:
      NODES:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(",")'
    requires:
      vars: [CLUSTER]
    preconditions:
      - talosctl --nodes {{.NODES}} get machineconfig
      - talosctl config info
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which jq talosctl

  kubeconfig:
    desc: Generate the kubeconfig for a Talos cluster [CLUSTER=main]
    cmd: talosctl kubeconfig --nodes {{.TALOS_CONTROLLER}} --force --force-context-name {{.CLUSTER}} {{.CLUSTER_DIR}}
    vars:
      TALOS_CONTROLLER:
        sh: talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1
    requires:
      vars: [CLUSTER]
    preconditions:
      - talosctl config info
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which jq talosctl

  apply-cluster:
    desc: Apply Talos config across the whole cluster [CLUSTER=main] [MODE=default]
    cmds:
      - for: { var: NODES }
        task: apply-node
        vars:
          IP: '{{.ITEM}}'
          MODE: '{{.MODE}}'
          CLUSTER: '{{.CLUSTER}}'
    vars:
      MODE: '{{.MODE | default "auto"}}'
      NODES:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(" ")'
    requires:
      vars: [CLUSTER]
    preconditions:
      - talosctl config info
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which jq talosctl

  upgrade-cluster:
    desc: Upgrade Talos across the whole cluster [CLUSTER=main]
    cmds:
      - for: { var: NODES }
        task: upgrade-node
        vars:
          IP: '{{.ITEM}}'
          CLUSTER: '{{.CLUSTER}}'
    vars:
      NODES:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(" ")'
    requires:
      vars: [CLUSTER]
    preconditions:
      - talosctl config info
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which jq talosctl

  reboot-cluster:
    desc: Reboot Talos across the whole cluster [CLUSTER=main] [MODE=default]
    cmds:
      - for: { var: NODES }
        task: reboot-node
        vars:
          IP: '{{.ITEM}}'
          MODE: '{{.MODE}}'
          CLUSTER: '{{.CLUSTER}}'
    vars:
      NODES:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(" ")'
    requires:
      vars: [CLUSTER]
    preconditions:
      - talosctl config info
      - test -f {{.CLUSTER_DIR}}/talosconfig
      - which jq talosctl

  down:
    internal: true
    cmds:
      - until kubectl wait cephcluster --for=jsonpath=.status.ceph.health=HEALTH_OK --timeout=10m --all --all-namespaces &>/dev/null; do sleep 5; done
      - until kubectl wait jobs --all --all-namespaces --for=condition=complete --timeout=5m &>/dev/null; do sleep 5; done
    preconditions:
      - which kubectl
