apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: debrid-api-token
stringData:
    DEBRID_API_TOKEN: ENC[AES256_GCM,data:NPvudCuvbscbEAUaQgEVcMxTPgWTEQj3TISjUesnamCENnQ0qBzFufK8s3IECr6ruGrP+g==,iv:Awjg6aIeB3NoV8J0dcSrCtorjmn6lY7oTLOv9VRlZrg=,tag:7K1s6HwAY+Yp0ihoDv59lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lz2u75apdq73zpxp039khxngs59jcca5ek8apc8c02eceg25asrq55u5dc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMUwwbFJaWmtKQnVzdWtu
            c1lhci9wZUV4ejNxa3RFbkRYT1BvTmErS1FzCkdSR0pkQ2EyejNWaEpUQ1h4VGNz
            L1dTa1M2Rmp6clpuMmE2dURBZEVhUXMKLS0tIHo5amZOWUx2YVp1ZHdGeXRxQVJn
            NUtqL29IQnNhUmFVK0RPMndicDhEamsKHfwFgALOTQBP3Wr/xFeEXIw4PuQd2HcT
            I59mtalMqy9uwBEGeSW/rOJRosbbQBS9WluYIR6CUkFZi/1cgYJPvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T09:03:54Z"
    mac: ENC[AES256_GCM,data:S0QBJ7OeIjEQOlqduNt7IOirHbwS3jbEsr32yyE4KdurGo61naFm6MIM/c/NAZBhvVuKqDCotb6m3WVMJ9HVXHm/oKgEs6vodVS8qVFLn7keqBaXfXYPApf+r8FY0oNDEHLI94u2GRuN6beTLbK1T17DDTRSgzVe+BEo1Qo8dyE=,iv:KQBsxF0DqAOOGKtVNVvcTsn5ndNnJsSJFvmzgz4FZtw=,tag:UuT+CN6lEVdgmgPegFjeyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
