---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
    - name: generic-device-plugin
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: 'true'
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.41.0.8994-f2c27da23@sha256:fe9ed1189617cd98106635c63ed39d40e4ec82535514e4a51a7c72e56b65c4dd
            env:
              TZ: America/Chicago
              # PLEX_ADVERTISE_URL: https://plex.mordex.io:443,http://10.30.0.100:32400
              PLEX_NO_AUTH_NETWORKS: 10.10.0.0/24
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds:
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegedEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - 'ALL'
            resources:
              requests:
                cpu: 100m
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi
      zurg:
        containers:
          zurg:
            image:
              repository: ghcr.io/mmberry96/zurg
              tag: 0.1.1@sha256:09a10b94bafbb8eb4ae912ff308fb98702ef5a21f34d97e41cbf1051c8cd5943
            envFrom:
              - secretRef:
                  name: debrid-api-token
            securityContext:
              allowPrivilegedEscalation: false
              capabilities:
                drop:
                  - 'ALL'
          rclone:
            image:
              repository: ghcr.io/mmberry96/rclone
              tag: 0.1.1@sha256:be7bedd4cff6b8e70caf681f33110504184e9fa85a49d2522b55148268f6191b
            args:
              - 'mount zurg:/ /data --allow-non-empty --allow-other --uid=65534 --gid=65534 --umask=002 --dir-cache-time 10s'
            dependsOn:
              - zurg
            securityContext:
              allowPrivilegedEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - 'ALL'
                add:
                  - 'SYS_ADMIN'
            resources:
              limits:
                squat.ai/fuse: 1
    service:
      plex:
        controller: plex
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.30.0.101
        ports:
          http:
            port: 32400
      zurg:
        controller: zurg
        type: ClusterIP
        ports:
          http:
            port: 9999
    route:
      http:
        kind: HTTPRoute
        parentRefs:
          - name: traefik-gateway
            sectionName: web
            namespace: network
        hostnames:
          - plex.home.mordex.io
        rules:
          - filters:
              - type: RequestRedirect
                requestRedirect:
                  scheme: https
      https:
        kind: HTTPRoute
        parentRefs:
          - name: traefik-gateway
            sectionName: websecure
            namespace: network
        hostnames:
          - plex.home.mordex.io
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: plex
                port: 32400
    persistence:
      config:
        existingClaim: plex
        advancedMounts:
          plex:
            plex:
              - path: /config/Library/Application Support/Plex Media Server
      zurg-config:
        type: configMap
        name: zurg-configmap
        advancedMounts:
          zurg:
            zurg:
              - path: /app/config.yml
                subPath: zurg
            rclone:
              - path: /config/rclone/rclone.conf
                subPath: rclone
      logs:
        type: emptyDir
        advancedMounts:
          plex:
            plex:
              - path: /config/Library/Application Support/Plex Media Server/Logs
          zurg:
            zurg:
              - path: /app/logs
      media:
        type: nfs
        server: truenas.home.mordex.io
        path: /mnt/storage0/media
        advancedMounts:
          plex:
            plex:
              - path: /media
                readOnly: true
      # torrents:
      #   existingClaim: plex-torrents
      #   advancedMounts:
      #     plex:
      #       plex:
      #         - path: /torrents
      #           readOnly: true
      #     zurg:
      #       zurg:
      #         - path: /app/data
      #       rclone:
      #         - path: /data
