---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./debrid.secret.sops.yaml
  - ./zurg-configmap.yaml
  - ./pvc.yaml
  - ./helm-release.yaml
# configMapGenerator:
#   - name: zurg-configmap
#     files:
#       - config.yaml=./configs/config.yaml
#       - rclone.conf=./configs/rclone.conf
#     options:
#       disableNameSuffixHash: true
replacements:
  - source:
      kind: Secret
      name: debrid-api-token
    targets:
      - select:
          kind: ConfigMap
          name: zurg-configmap
        fieldPaths:
          - data.zurg
