---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-torrents
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 25Gi
  storageClassName: ceph-block
