kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_OPENMETEO_LABEL: ENC[AES256_GCM,data:v5IOsqJ5NlWJNsie+g==,iv:9XlUBY8EqawsTvPBIyxOvYIm6nung1P1oUV83aTPRxg=,tag:5eEk2RVDzc1SS7wuSSus6g==,type:str]
    HOMEPAGE_VAR_OPENMETEO_LAT: ENC[AES256_GCM,data:tbsAHX1ozkas,iv:SeGByzGg/ZluHPsJoZeJiTSupMjPPFWFV+9eEpFxkUY=,tag:DaFrJziGh436t3MtVMAeKg==,type:str]
    HOMEPAGE_VAR_OPENMETEO_LONG: ENC[AES256_GCM,data:oOEbKjDmdb6kgg==,iv:mR/J5lDdcCpZaYjBeV7IOfuPt/4TsKS5i7OaKgm9opE=,tag:IajuF+v3dqVgJ10A431fxQ==,type:str]
    HOMEPAGE_VAR_OPNSENSE_USERNAME: ENC[AES256_GCM,data:HrfbHED3wqtBaq6ydhDFFU96SetZwbZHsi9Jo40BG9KwbfhaJC3/ly0SxAoJUAyxlF3bEMwVv2zcDR2BSVg/AEBBQE/kTW9k31cznELeP2M=,iv:6Cx/YkDl6/5zzAcXjuar6a8QIs7/REwebhu/SvfVs9A=,tag:FNI9YilDD+T1qDfO4C+yoQ==,type:str]
    HOMEPAGE_VAR_OPNSENSE_PASSWORD: ENC[AES256_GCM,data:+RqjMYaaDm+c71LHIzxobtqxcRUqaRcqFgtMUesvYnSGycNVzXJL7jTR/+Xu4HBDYBvg/ro56WiLeRqlv8V6iVT8B2s1ejSzfjeRYGikehw=,iv:md00lo/moL02tYuZ9ctlMQBDa78fAUfCkySNRuB4i9U=,tag:VjauiuKlBB7g02ilmd1+vA==,type:str]
    HOMEPAGE_VAR_PIHOLE_API_KEY: ENC[AES256_GCM,data:CSZ4N4g220emD7BADF88SZwUz+gUdZzWPliBPNA+/6y/QdHUyqNxe6C6O/vfqnt6izWNkDamBv9Kjxs+KYH04Q==,iv:xP/aePHTf+pD5+B27YgrZxABWxL92Zc2ADCjaa0r6fo=,tag:WUn1EziUu8aFbblxULTufQ==,type:str]
    HOMEPAGE_VAR_TRUENAS_API_KEY: ENC[AES256_GCM,data:j4QGKeqGu+DIdBa02Ba4LqymD+34ASzzbsbMkVyciFWLNvqVRJuEWyc+DwI+knmUxrvKkYVICBPYdjEi47kOfsTc,iv:Op4kBzHsPPll3JLVBvNuHVk6AZEKI/mAXELW45Eaohs=,tag:ahr9cruEZwW4tYRvonJakg==,type:str]
    HOMEPAGE_VAR_UNIFI_USERNAME: ENC[AES256_GCM,data:18WVrZqmPnwkbGtUbpE=,iv:RPT/gxufxdpGfSrynPB5YQA4xGHB6WGhD3fi4igxbNk=,tag:FkE0+d0NbS29GIK9gWLzrQ==,type:str]
    HOMEPAGE_VAR_UNIFI_PASSWORD: ENC[AES256_GCM,data:j7HJiLSX5x0M1QcebgsUDZ9UQw==,iv:i/A50P1BxDAvH9WfaUmMDJIt9eZT8m2+atDbfOuh7yM=,tag:txud2Y/DHbHSCavo3sW14g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lz2u75apdq73zpxp039khxngs59jcca5ek8apc8c02eceg25asrq55u5dc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbmEvdWR6ZGlVeUNMVzJw
            RmZOcnRmRzJNWThzUkVXYmkrUjNoSGE5RFdFCkRwaEM0SDBSYlJTZFlTY25rN3lP
            K09neGxKUUZpeWo0WmI5RzV6dEhrSW8KLS0tIHhoMFl3YzFxQVVlM3VmRnN3d1VD
            eitUZ21HczFyRUhpZmVmaE1XOTdKVXcKePhq/wDSoO5FPX3vsBkv92w6FWX3/XAb
            6ZUc4R08Kia3g0ysb70LL0PFeVPka44ZVwjd56VQABPgOOPhbo9ZXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-30T05:07:06Z"
    mac: ENC[AES256_GCM,data:CIyghlrhzpzfw8MC1JGValNPFTT5+aRpIDgbBcrHK6tXqGUiWWaH2Irixw/s1YcjDGtsyjfq2H8D6xJug7YggQc+GDbq2J7JyGrM4hwN/AfKQLzpkWLdzpu87s8sak8yIJFx76wfRlXCwZx5qGsu6M4FzH83tA3ReweivEUD0zs=,iv:w5fRZbMBaJIlAS4k/qoYWXajOt6NxUGP9mNHBHdq7VA=,tag:EpEHUapJmS6NWyYuz2nGKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
