# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_OPENMETEO_LABEL: '{{ .OPENMETEO_LABEL }}'
        HOMEPAGE_VAR_OPENMETEO_LAT: '{{ .OPENMETEO_LAT }}'
        HOMEPAGE_VAR_OPENMETEO_LONG: '{{ .OPENMETEO_LONG }}'
        HOMEPAGE_VAR_OPNSENSE_USERNAME: '{{ .OPNSENSE_USERNAME }}'
        HOMEPAGE_VAR_OPNSENSE_PASSWORD: '{{ .OPNSENSE_PASSWORD }}'
        HOMEPAGE_VAR_PIHOLE_API_KEY: '{{ .PIHOLE_API_KEY}}'
        HOMEPAGE_VAR_TRUENAS_API_KEY: '{{ .TRUENAS_API_KEY}}'
        HOMEPAGE_VAR_UNIFI_USERNAME: '{{ .UNIFI_USERNAME }}'
        HOMEPAGE_VAR_UNIFI_PASSWORD: '{{ .UNIFI_PASSWORD }}'
  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: opnsense
    - extract:
        key: pihole
    - extract:
        key: truenas
    - extract:
        key: unifi
