---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      homepage:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: latest
            envFrom:
              - secretRef:
                  name: homepage-secret
            ports:
              - name: http
                containerPort: 3000
                protocol: TCP
    service:
      homepage:
        controller: homepage
        type: ClusterIP
        ports:
          http:
            port: 3000
    route:
      http:
        kind: HTTPRoute
        parentRefs:
          - name: traefik-gateway
            sectionName: web
            namespace: network
        hostnames:
          - home.mordex.io
        rules:
          - filters:
              - type: RequestRedirect
                requestRedirect:
                  scheme: https
      https:
        kind: HTTPRoute
        parentRefs:
          - name: traefik-gateway
            sectionName: websecure
            namespace: network
        hostnames:
          - home.mordex.io
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: homepage
                port: 3000
    persistence:
      custom-js:
        type: configMap
        name: homepage-configmap
        globalMounts:
          - path: /app/config/custom.js
            subPath: custom.js
      custom-css:
        type: configMap
        name: homepage-configmap
        globalMounts:
          - path: /app/config/custom.css
            subPath: custom.css
      bookmarks:
        type: configMap
        name: homepage-configmap
        globalMounts:
          - path: /app/config/bookmarks.yaml
            subPath: bookmarks.yaml
      docker:
        type: configMap
        name: homepage-configmap
        globalMounts:
          - path: /app/config/docker.yaml
            subPath: docker.yaml
      kubernetes:
        type: configMap
        name: homepage-configmap
        globalMounts:
          - path: /app/config/kubernetes.yaml
            subPath: kubernetes.yaml
      services:
        type: configMap
        name: homepage-configmap
        globalMounts:
          - path: /app/config/services.yaml
            subPath: services.yaml
      settings:
        type: configMap
        name: homepage-configmap
        globalMounts:
          - path: /app/config/settings.yaml
            subPath: settings.yaml
      widgets:
        type: configMap
        name: homepage-configmap
        globalMounts:
          - path: /app/config/widgets.yaml
            subPath: widgets.yaml
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
