---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.ios/v2
kind: HelmRelease
metadata:
  name: prometheus-adaptor
spec:
  chartRef:
    kind: OCIRepository
    name: prometheus-adaptor
  interval: 1h
  values:
    prometheus:
      url: http://prometheus-operated.o11y.svc.cluster.local
    rules:
      default: false
      external:
        - seriesQuery: '{__name__="probe_success"}'
          resources:
            namespaced: false
          name:
            as: probe_success
          metricsQuery: max_over_time(<<.Series>>{<<.LabelMatchers>>}[1m])
