title: Mordex.io Homepage

background:
  image: https://plus.unsplash.com/premium_photo-1675826774817-fe983ceb0475?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  blur: sm
  saturate: 100
  brightness: 50
  opacity: 100

theme: dark
color: slate

useEqualHeights: true

statusStyle: dot

layout:
  Infrastructure:
    style: row
    columns: 4
  Networking:
    style: row
    columns: 3
  Storage:
    style: row
