- openmeteo:
    label: '{{HOMEPAGE_VAR_OPENMETEO_LABEL}}'
    latitude: '{{HOMEPAGE_VAR_OPENMETEO_LAT}}'
    longitude: '{{HOMEPAGE_VAR_OPENMETEO_LONG}}'
    timezone: America/Chicago
    units: imperial
    cache: 5
- datetime:
    text_size: 2xl
    format:
      timeStyle: short
      hour12: true
