---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-mordex-io
  namespace: default
spec:
  secretName: home-mordex-io-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '*.home.mordex.io'
  dnsNames:
    - 'home.mordex.io'
    - '*.home.mordex.io'
