apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |
    {
      'cniVersion': '0.3.1',
      'type': 'ipvlan',
      'master': 'eno2',
      'ipam': {
        'type': 'static',
        'routes': [
          { 'dst': '10.20.0.0/24', 'gw': '10.20.0.1' }
        ]
      }
    }
