---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app internal-external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider:
      name: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://10.30.0.10
      - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret internal-external-dns-secret
            key: *name
    extraArgs:
      - --ignore-ingress-tls-spec
    registry: noop
    triggerLoopEvent: true
    policy: upsert-only
    sources:
      - ingress
      - service
      # - gateway-httproute
    domainFilters:
      - mordex.io
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
