---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: v32.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    deployment:
      replicas: 3

    ingressClass:
      name: traefik-internal

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.home.mordex.io`)
        entryPoints: ['websecure']
        middlewares:
          - name: traefik-internal-dashboard-basicauth

    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        # ingressClass: traefik-internal

    globalArguments:
      - '--global.sendanonymoususage=false'
      - '--global.checknewversion=false'

    additionalArguments:
      - '--serverstransport.insecureskipverify=true'
      - '--providers.kubernetesingress.ingressclass=traefik-internal'
      - '--log.level=DEBUG'

    ports:
      web:
        redirectTo:
          port: websecure
          priority: 10
      websecure:
        http3:
          enabled: true
        advertisedPort: 4443

    service:
      spec:
        loadBalancerIP: 10.30.0.100
