---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      generic-device-plugin:
        type: daemonset
        containers:
          app:
            image:
              repository: squat/generic-device-plugin
              tag: 36bfc606bba2064de6ede0ff2764cbb52edff70d@sha256:ba6f0b4cf6c858d6ad29ba4d32e4da11638abbc7d96436bf04f582a97b2b8821
            args:
              - --device
              - |
                name: fuse
                groups:
                  - paths:
                    - path: /dev/fuse
            securityContext:
              # allowPrivilegedEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - 'ALL'
    persistence:
      device-plugin:
        type: hostPath
        hostPath: /var/lib/kubelet/device-plugins
      dev:
        type: hostPath
        hostPath: /dev
