---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/traefik/traefik/v3.0/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.crds.yaml
