---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.16.4
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: snapshot-controller
      namespace: volsync-system
  values:
    csi:
      cephFSKernelMountOptions: ms_mode=prefer-crc
      # NOTE: Enable the driver and snapshotter if you want to use CephFS
      enableCephfsDriver: false
      enableCephfsSnapshotter: false
      enableLiveness: true
      serviceMonitor:
        enabled: true
    enableDiscoveryDaemon: true
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 100m #unchangeable
        memory: 128Mi #unchangeable
      limits: {}
