---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: 'Yes'
  blocks:
    - # Controller VIP: 10.30.0.40
      start: 10.30.0.100
      stop: 10.30.0.119
