apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:cJba0Loz7LDBTmpLLDJ1dyARiCYmJX551GKMEhJ3poKQnaJHjdUS/w==,iv:w6WXzVMmQ8dPx4eyP6oaNq1VzEB47wxPMkKpHsDVqkk=,tag:L4yx5vD3LFT4bXZs5U6U/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lz2u75apdq73zpxp039khxngs59jcca5ek8apc8c02eceg25asrq55u5dc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQUovY29OSnRDcGRyMjVS
            TmRQSlBXWDBpZ29DVDU0Nk9xemdLcTJ1NmhnCnJhcTNybW9sQTkyRTdBalhrckZl
            YmdtQzZMQzRDN1FEN1ByTkVrOEQvNkkKLS0tIGQ3aGdqTXlMTDhpSkQ5em54OUxw
            Q3M3a2RLZUc2ODRKVytCQ2pPTUxRS3MKxsW9KZtAa85NYQZEY6uUwzRAu1vDTLky
            MIieHJsERjrIgKAanTYUXPIWL0e7zyrP7UX6rKCeWKw4/z349l96dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T08:08:17Z"
    mac: ENC[AES256_GCM,data:RIC8BP1QITsOfeHkDG3Q21q2ajjBb5+Kc9auIKwHc+xIqsrI8hJB2Sf85SJa4Ab8SD0tEbr8aYzIHKYUhnWUqY3FA/0uHZqc/ha4oTBOBuGGIkh3Wzm48QbL6JaG+dpGqsPmu+badHnQKqAKM6PpysbyU5j5NvP4xoF2NpTj6fs=,iv:hxjK007iwKV/K8uDX5Dg4YLcNwSUzsmqrbearJ/eark=,tag:ugviztmhO/iBoz9/f1nUgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
